[2022-04-27T20:05:26.234] [ERROR] error - Servidor escuchando en puerto 8080
[2022-04-27T20:05:32.390] [ERROR] error - Servidor escuchando en puerto 8080
[2022-04-27T20:24:54.484] [ERROR] error - ruta '/' metodo GET no implementado
[2022-04-27T20:37:09.823] [ERROR] error - Error: No recipients defined
    at SMTPConnection._formatError (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\nodemailer\lib\smtp-connection\index.js:784:19)
    at SMTPConnection._setEnvelope (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\nodemailer\lib\smtp-connection\index.js:1001:34)
    at SMTPConnection.send (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\nodemailer\lib\smtp-connection\index.js:615:14)
    at sendMessage (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\nodemailer\lib\smtp-transport\index.js:227:28)
    at C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\nodemailer\lib\smtp-transport\index.js:285:25
    at SMTPConnection._actionAUTHComplete (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\nodemailer\lib\smtp-connection\index.js:1550:9)
    at SMTPConnection.<anonymous> (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\nodemailer\lib\smtp-connection\index.js:540:26)
    at SMTPConnection._processResponse (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\nodemailer\lib\smtp-connection\index.js:947:20)
    at SMTPConnection._onData (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\nodemailer\lib\smtp-connection\index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\nodemailer\lib\smtp-connection\index.js:189:44) {
  code: 'EENVELOPE',
  command: 'API'
}
[2022-04-27T20:37:10.723] [ERROR] error - RestException [Error]: Authenticate
    at success (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 401,
  code: 20003,
  moreInfo: 'https://www.twilio.com/docs/errors/20003',
  details: undefined
}
[2022-04-27T20:38:06.095] [ERROR] error - RestException [Error]: Authenticate
    at success (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 401,
  code: 20003,
  moreInfo: 'https://www.twilio.com/docs/errors/20003',
  details: undefined
}
[2022-04-27T20:42:32.546] [ERROR] error - RestException [Error]: Authenticate
    at success (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 401,
  code: 20003,
  moreInfo: 'https://www.twilio.com/docs/errors/20003',
  details: undefined
}
[2022-04-27T20:43:37.321] [ERROR] error - RestException [Error]: Authenticate
    at success (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 401,
  code: 20003,
  moreInfo: 'https://www.twilio.com/docs/errors/20003',
  details: undefined
}
[2022-04-27T20:44:08.629] [ERROR] error - RestException [Error]: Authenticate
    at success (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 401,
  code: 20003,
  moreInfo: 'https://www.twilio.com/docs/errors/20003',
  details: undefined
}
[2022-04-27T20:54:29.361] [ERROR] error - RestException [Error]: The 'To' number 456 is not a valid phone number.
    at success (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 400,
  code: 21211,
  moreInfo: 'https://www.twilio.com/docs/errors/21211',
  details: undefined
}
[2022-04-27T20:54:30.223] [ERROR] error - RestException [Error]: The From phone number +14155238886 is not a valid, SMS-capable inbound phone number or short code for your account.
    at success (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 400,
  code: 21606,
  moreInfo: 'https://www.twilio.com/docs/errors/21606',
  details: undefined
}
[2022-04-27T20:56:19.802] [ERROR] error - RestException [Error]: The 'To' number 456 is not a valid phone number.
    at success (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 400,
  code: 21211,
  moreInfo: 'https://www.twilio.com/docs/errors/21211',
  details: undefined
}
[2022-04-27T20:56:20.715] [ERROR] error - RestException [Error]: The number  is unverified. Trial accounts cannot send messages to unverified numbers; verify  at twilio.com/user/account/phone-numbers/verified, or purchase a Twilio number to send messages to unverified numbers.
    at success (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 400,
  code: 21608,
  moreInfo: 'https://www.twilio.com/docs/errors/21608',
  details: undefined
}
[2022-04-27T20:57:47.548] [ERROR] error - RestException [Error]: The 'To' number 456 is not a valid phone number.
    at success (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 400,
  code: 21211,
  moreInfo: 'https://www.twilio.com/docs/errors/21211',
  details: undefined
}
[2022-04-27T21:01:33.609] [ERROR] error - RestException [Error]: The 'To' number 456 is not a valid phone number.
    at success (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\Alan\Documents\desafio.clase.36.tercer.preentrega\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 400,
  code: 21211,
  moreInfo: 'https://www.twilio.com/docs/errors/21211',
  details: undefined
}
